# cmake/generate_config_header.cmake
#
# This script programmatically generates the final 'config.h' header file.
# It includes the help string from each option as a comment above its #define,
# making the header self-documenting.

set(OUTPUT_HEADER_PATH "${CMAKE_BINARY_DIR}/config.h")
set(FILE_CONTENT "#pragma once\n\n")
string(APPEND FILE_CONTENT "// This file is auto-generated by CMake. DO NOT EDIT.\n")
string(APPEND FILE_CONTENT "// It is generated based on the settings in cmake/options.cmake\n")
string(APPEND FILE_CONTENT "// and the user's 'config' file.\n")

# Loop through every option defined in our central list.
foreach(option ${PROJECT_CONFIG_OPTIONS})
    # Get the help string associated with the option.
    get_property(HELP_STRING CACHE ${option} PROPERTY HELPSTRING)

    # Determine the numeric value (1 or 0) based on the option's boolean state.
    if(${option})
      set(NUMERIC_VALUE 1)
    else()
      set(NUMERIC_VALUE 0)
    endif()

    # Append the formatted comment and #define to our file content string.
    string(APPEND FILE_CONTENT "\n// ${HELP_STRING}\n")
    if(${option})
      string(APPEND FILE_CONTENT "#define ${option}\n")
    else()
      string(APPEND FILE_CONTENT "#undef ${option}\n")
    endif()
    # string(APPEND FILE_CONTENT "#define ${option} ${NUMERIC_VALUE}\n")
endforeach()

# Write the completed content to the final config.h file.
file(WRITE ${OUTPUT_HEADER_PATH} "${FILE_CONTENT}")
message(STATUS "Generated self-documenting config header: ${OUTPUT_HEADER_PATH}")
